server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 212723010132-ii7hbqov40direv4hqp1a0b2gap2h0i3.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#logging:
#  level:
#    org.springframework.security: TRACE
#    org.springframework.security.oauth2: DEBUG

